# Generated by Django 2.2.2 on 2019-12-14 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='NameLess', max_length=100, verbose_name='название')),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='лайки')),
                ('url', models.URLField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
