# Generated by Django 2.2.2 on 2019-12-14 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videostream', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myvideo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='myvideo',
            name='slug',
            field=models.SlugField(help_text='уникальная ссылка', unique=True),
        ),
        migrations.AlterField(
            model_name='myvideo',
            name='title',
            field=models.CharField(default='NameLess', help_text='Название видео', max_length=100, verbose_name='название'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videostream.MyVideo')),
            ],
        ),
    ]
